### ISSUE TITLE
Publish important macros from `Moshi`

### ISSUE THREAD

**Issue by jariji** [Roger-luo/Moshi.jl#12]
I propose exporting `@data` and `@match` and maybe `@derive` from `Moshi`. It's more convenient than learning about `Moshi.Data`.

**Comment by Roger-luo** [comment]
Moshi uses [Jieko](https://github.com/Roger-luo/Jieko.jl) to define an interface. Exporting names by default is harmful; if you want to port all names, you can always do this explicitly via `using Moshi.Data.Prelude`. Thus, this doesn't make sense here and I don't think that will be a good practice we should encourage in Julia code.

**Comment by jariji** [comment]
Making Moshi more convenient to use will cause it to be used more, which will be a benefit to Julia code in general.

How about at least allowing `using Moshi: @data, @match`?
