### ISSUE TITLE
Remove `adt.Type` and `adt.Variant`

### ISSUE THREAD

**Issue by jariji** [Roger-luo/Moshi.jl#13]
It would be nice if the only properties of an adt were its variants. The other attributes `Type` and `Variant` can be extracted with functions `adt(x)` and `variant(x)` if necessary.

**Comment by Roger-luo** [comment]
I don't think this is possible, I have been looking for a good solution in the past 2 years... say we have

```julia
@data Message begin
   Move(Int)
   Color(Int, Int, Int)
end
```

You cannot annotate a function with `adt(Message)`. This is not overloadable. And I don't think writing extra brackets is better than the current solution. I'm going to close this, but feel free to come back with more concrete proposals.

**Comment by jariji** [comment]
We can dispatch on `Val(::Module)` like this:

```jl
julia> adt(m::Module) = adtval(Val(m));
       adtval(::Val{Message}) = Message.Type;

julia> adt(Message)
Main.Message.Type
```
