### ISSUE TITLE
Bind `Type` to a more informative name

### ISSUE THREAD

**Issue by MasonProtter** [Roger-luo/Moshi.jl#17]
Currently we have
```julia
julia> using Moshi.Data: @data

julia> @data List{T} begin
           Nil
           Cons(T, List{T})
       end

julia> typeof(List.Nil())
Main.List.Type{Union{}}
```
I think maybe this should instead be something like
```julia
module List
struct var"typeof(List)"{T}
    ...
end
const Type{T} = var"typeof(List)"{T}
end
```
so that it's a bit more informative from the outset what this `Type` object is e.g. when printing the type of something.

**Comment by Roger-luo** [comment]
Yeah I agree this would be a better printing name.
