### ISSUE TITLE
Text representation of data types?

### ISSUE THREAD

**Issue by jonalm** [Roger-luo/Moshi.jl#21]
Hi there, I'm using `@data` to make simple enums a la,
```julia
@data MyEnum begin
    A
    B
    C
end
```

`print`, `show` and `repr` on `MyEnum.A()` returns `Main.MyEnum.Type(Main.MyEnum.var"##Storage#A"())`. Is there a method which returns a more user friendly string representation, e.g. `string(MyEnum.A()) == "MyData.A"? And tangentially related, is there a a way to serialize an enum value?

**Comment by Roger-luo** [comment]
Yes, see #16

**Comment by Roger-luo** [comment]
ah, actually my bad I haven't finished the documentation. I'll reopen #16
