### ISSUE TITLE
Clarify subtyping

### ISSUE THREAD

**Issue by nandoconde** [Roger-luo/Moshi.jl#27]
Reading the docs it does not seem too clear how (if?) subtyping is implemented for `@data`.

First, the syntax for the super type only says `[ <supertype> ]`, which errors if written like that.
I think it should be `[ <: <supertype> ]`.

Second, even if written like that, no supertype/subtype structure is created:

```julia
julia> @data MyADT <: MyAbstractType begin
           ADT1
           ADT2
       end
Main.MyADT

julia> subtypes(MyAbstractType)
Any[]

julia> supertype(MyADT.Type)
Any

julia> supertype(MyADT.Variant)
Any

julia> supertype(MyADT.ADT1)
Main.MyADT.Variant
```

Maybe some light can be shed into this?

**Comment by Roger-luo** [comment]
hmm this might be a bug, `MyADT.Type` should be a subtype of `MyAbstractType`.

**Comment by nandoconde** [comment]
I would attempt a PR, but I really don't understand a quarter of the code in the repo, it's all metaprogramming 🥲

**Comment by nandoconde** [comment]
Okay, maybe it lacks the `supertype` argument here, in the call to JLStruct. Maybe an if/else must protect it in case there is no supertype at all?

**Comment by nandoconde** [comment]
I tried to implement it and I ran into errors regarding namespaces (the abstract type is defined outside the new baremodule and thus I cannot add it without importing it from Main).

However, I can open a PR with a test if you want 😄

**Comment by Roger-luo** [comment]
ah yes, it's gone somehow! Yeah please feel free to open one, I can help you fix the `baremodule` issue in the PR!

**Comment by nandoconde** [comment]
We can continue the conversation in #28 😄

**Comment by nandoconde** [comment]
Great! This can be closed now  💯
