### ISSUE TITLE
Doc link broken

### ISSUE THREAD

**Issue by brianguenter** [Roger-luo/Moshi.jl#3]
This link gives a 404 page not found: https://rogerluo.dev/Moshi.jl/start/match/builtin

**Comment by Roger-luo** [comment]
which page is referencing this link?

**Comment by hmyuuu** [comment]
It's referenced at https://github.com/Roger-luo/Moshi.jl/blob/9f1010a25316ad257d20ad47b402659ef47e1f52/docs/src/content/docs/start/match.mdx?plain=1#L61-L62

**Comment by hmyuuu** [comment]
The correct link should be here I guess?
https://github.com/Roger-luo/Moshi.jl/blob/9f1010a25316ad257d20ad47b402659ef47e1f52/docs/src/content/docs/match/syntax.mdx?plain=1#L23-L26

**Comment by Roger-luo** [comment]
I just fixed a few ones, and please feel free to open PR to fix them if you see any!
